# Generated by Django 4.2.11 on 2024-05-17 11:12

from django.db import migrations, models
import ican.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='businessdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=50)),
                ('gstin_number', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=30)),
                ('company_address', models.CharField(max_length=30)),
                ('pincode', models.CharField(max_length=30)),
                ('contact_number', models.IntegerField(max_length=30)),
                ('email_id', models.EmailField(max_length=30)),
                ('photocopy', models.ImageField(blank=True, null=True, upload_to=ican.models.getFileName)),
                ('website_link', models.CharField(max_length=100)),
                ('gmaps_link', models.CharField(max_length=100)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
