# Generated by Django 4.2.11 on 2024-05-17 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0002_businessdata_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='contact_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
