# Generated by Django 4.2.11 on 2024-05-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0003_alter_businessdata_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='contact_number',
            field=models.CharField(max_length=10),
        ),
    ]
