# Generated by Django 4.2.11 on 2024-05-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0004_alter_businessdata_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdata',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='businessdata',
            name='open_time',
        ),
        migrations.AddField(
            model_name='businessdata',
            name='business_work_type',
            field=models.CharField(default='Full-time', max_length=30),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='email_id',
            field=models.EmailField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='gmaps_link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='gstin_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='website_link',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
