# Generated by Django 4.2.11 on 2024-05-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0005_remove_businessdata_close_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='description',
            field=models.CharField(default='Share moments. Share life.', max_length=500),
        ),
        migrations.AlterField(
            model_name='businessdata',
            name='company_name',
            field=models.CharField(max_length=100),
        ),
    ]
