# Generated by Django 4.2.11 on 2024-05-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0006_businessdata_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='business_work_type',
            field=models.CharField(max_length=30),
        ),
    ]
