# Generated by Django 4.2.11 on 2024-05-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0007_alter_businessdata_business_work_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdata',
            name='username_post',
            field=models.CharField(default='retail', max_length=30),
        ),
    ]
