# Generated by Django 4.2.11 on 2024-05-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0008_businessdata_username_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='username_post',
            field=models.CharField(max_length=30),
        ),
    ]
