# Generated by Django 4.2.11 on 2024-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0009_alter_businessdata_username_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='company_address',
            field=models.CharField(max_length=100),
        ),
    ]
