# Generated by Django 4.2.11 on 2024-05-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0010_alter_businessdata_company_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='company_name',
            field=models.TextField(max_length=100),
        ),
    ]
