# Generated by Django 4.2.11 on 2024-05-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0012_alter_businessdata_company_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessdata',
            old_name='company_address',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='businessdata',
            name='town_address',
            field=models.CharField(default='-', max_length=150),
        ),
    ]
