# Generated by Django 4.2.11 on 2024-05-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ican', '0013_rename_company_address_businessdata_street_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessdata',
            name='town_address',
            field=models.CharField(max_length=150),
        ),
    ]
